### ISSUE TITLE
Add config for dotalytics-api host and port

### ISSUE THREAD

**Issue by trevormccasland** [trevormccasland/dotalytics#6]
Currently the host name and port are hard coded in the repository, we should support a config file that specifies where the API is running

**Comment by ighmaZ** [comment]
would love to work on this

**Comment by trevormccasland** [comment]
@ighmaZ  Thanks for your interest! Let me know if you have any questions on how to run the dotalytics and dotalytics-api services or if you have any improvements for the README.

We recently switched to using webpack for dotalytics so it runs on the default port 8080. The Readme currently mentions port 3000 so that may be a little confusing. 

Edit: I updated to readme to read 8080 now.

**Comment by ighmaZ** [comment]
hi @trevormccasland ! i am new to open source, i am actually getting confused what needs to be done here

**Comment by trevormccasland** [comment]
What needs to be done for this issue to be completed is this hard-coded host and port[1] should be refactored into a config file.

We probably want a `config.json` file to be added in the root of the project that looks like this:
```
{
  "host": "localhost"
  "port": 8888
}
```
Then we probably want a typescript interface defined to use in the project (you can define a types.ts file and put it in there), that should look like this:
```
export interface Config {
  host: string
  port: number
}
```
Then lastly, we should load the config and use the type in the matchesClient.ts file:
```
import config from './config.json';
import Config from './types.ts'
// I'm not 100% sure on how to use the type here, this could be something you can figure out for the project!
const projectConfig: Config = config
...
const url = `http://${projectConfig.host}:${projectConfig.port}/matches?account_id=${accountId}&matches_requested=${matchesRequested}`
```
[1] https://github.com/trevormccasland/dotalytics/blob/main/src/services/matchesClient.ts#L88

Hopefully that answers your question!

**Comment by ighmaZ** [comment]
@trevormccasland ! this was helpful! i'll give my best

**Comment by ighmaZ** [comment]
hi @trevormccasland ! i have done most of the things so far just getting confused at matchesClients.ts

**Comment by trevormccasland** [comment]
Thanks for your pull request, I made some comments. After the issues are fixed I'll merge it.

**Comment by ighmaZ** [comment]
@trevormccasland ! i have made the corrections. please check
